# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dea08323450014449ae5cdb7d0e10f9d7938adc25a99bb4cccb2bb03ba0176091127b299f1cf528efecb41be15399334a450d19125187e1262ead0a137c0c83
  jwt_secret: 'even more super random key'
  jwt_expiration_hours: 10000
test:
  secret_key_base: c50774552cae59722adced44367b0522fb6819a43e2fef130e7018b72a2f5b7ecaefbc43824d25d4c9bac545ef930f6894bef6711f64141cd6f475f325c65839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6dea08323450014449ae5cdb7d0e10f9d7938adc25a99bb4cccb2bb03ba0176091127b299f1cf528efecb41be15399334a450d19125187e1262ead0a137c0c83
  jwt_secret: 'even more super random key'
  jwt_expiration_hours: 10000
